[project]
name = "professional-alter-ego"
version = "1.0.0"
description = "A chatbot that emulates my professional me!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests==2.33.1",
    "python-dotenv==1.2.2",
    "gradio==6.14.0",
    "pypdf==6.10.2",
    "openai==2.36.0",
    "openai-agents==0.17.0",
    "llama-index-core",
    "llama-index-embeddings-openai",
    "llama-index-vector-stores-qdrant",
    "llama-index-readers-file",
    "qdrant-client",
    "arize-phoenix",
    "openinference-instrumentation-llama-index",
    "openinference-instrumentation-openai",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
